// Code generated by ogen, DO NOT EDIT.

package api

import (
	"io"

	"github.com/go-faster/errors"
	"github.com/google/uuid"
)

// Body of the POST /deposits request.
// Ref: #/components/schemas/depositPostBody
type DepositPostBody struct {
	// Internal Id of the deposit.
	ID uuid.UUID `json:"id"`
	// Deposit amount.
	Amount float64 `json:"amount"`
	// Deposit currency.
	Currency string `json:"currency"`
	// The customer that received the deposit.
	CustomerId uuid.UUID `json:"customerId"`
	// Id assigned to the operation by the external payment provider.
	ExternalId uuid.UUID `json:"externalId"`
}

// GetID returns the value of ID.
func (s *DepositPostBody) GetID() uuid.UUID {
	return s.ID
}

// GetAmount returns the value of Amount.
func (s *DepositPostBody) GetAmount() float64 {
	return s.Amount
}

// GetCurrency returns the value of Currency.
func (s *DepositPostBody) GetCurrency() string {
	return s.Currency
}

// GetCustomerId returns the value of CustomerId.
func (s *DepositPostBody) GetCustomerId() uuid.UUID {
	return s.CustomerId
}

// GetExternalId returns the value of ExternalId.
func (s *DepositPostBody) GetExternalId() uuid.UUID {
	return s.ExternalId
}

// SetID sets the value of ID.
func (s *DepositPostBody) SetID(val uuid.UUID) {
	s.ID = val
}

// SetAmount sets the value of Amount.
func (s *DepositPostBody) SetAmount(val float64) {
	s.Amount = val
}

// SetCurrency sets the value of Currency.
func (s *DepositPostBody) SetCurrency(val string) {
	s.Currency = val
}

// SetCustomerId sets the value of CustomerId.
func (s *DepositPostBody) SetCustomerId(val uuid.UUID) {
	s.CustomerId = val
}

// SetExternalId sets the value of ExternalId.
func (s *DepositPostBody) SetExternalId(val uuid.UUID) {
	s.ExternalId = val
}

// NewOptUUID returns new OptUUID with value set to v.
func NewOptUUID(v uuid.UUID) OptUUID {
	return OptUUID{
		Value: v,
		Set:   true,
	}
}

// OptUUID is optional uuid.UUID.
type OptUUID struct {
	Value uuid.UUID
	Set   bool
}

// IsSet returns true if OptUUID was set.
func (o OptUUID) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptUUID) Reset() {
	var v uuid.UUID
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptUUID) SetTo(v uuid.UUID) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptUUID) Get() (v uuid.UUID, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptUUID) Or(d uuid.UUID) uuid.UUID {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// A text message describing an error.
// Ref: #/components/schemas/errorMessage
type PatchWithdrawalBadRequest struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s PatchWithdrawalBadRequest) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*PatchWithdrawalBadRequest) patchWithdrawalRes() {}

// PatchWithdrawalOK is response for PatchWithdrawal operation.
type PatchWithdrawalOK struct{}

func (*PatchWithdrawalOK) patchWithdrawalRes() {}

// A text message describing an error.
// Ref: #/components/schemas/errorMessage
type PostDepositBadRequest struct {
	Data io.Reader
}

// Read reads data from the Data reader.
//
// Kept to satisfy the io.Reader interface.
func (s PostDepositBadRequest) Read(p []byte) (n int, err error) {
	if s.Data == nil {
		return 0, io.EOF
	}
	return s.Data.Read(p)
}

func (*PostDepositBadRequest) postDepositRes() {}

// PostDepositCreated is response for PostDeposit operation.
type PostDepositCreated struct{}

func (*PostDepositCreated) postDepositRes() {}

// Body of the PATH /withdrawal request.
// Ref: #/components/schemas/withdrawalPatchBody
type WithdrawalPatchBody struct {
	// Id assigned to the operation by the external payment provider.
	ExternalId OptUUID `json:"externalId"`
	// Withdrawal status.
	Status WithdrawalPatchBodyStatus `json:"status"`
}

// GetExternalId returns the value of ExternalId.
func (s *WithdrawalPatchBody) GetExternalId() OptUUID {
	return s.ExternalId
}

// GetStatus returns the value of Status.
func (s *WithdrawalPatchBody) GetStatus() WithdrawalPatchBodyStatus {
	return s.Status
}

// SetExternalId sets the value of ExternalId.
func (s *WithdrawalPatchBody) SetExternalId(val OptUUID) {
	s.ExternalId = val
}

// SetStatus sets the value of Status.
func (s *WithdrawalPatchBody) SetStatus(val WithdrawalPatchBodyStatus) {
	s.Status = val
}

// Withdrawal status.
type WithdrawalPatchBodyStatus string

const (
	WithdrawalPatchBodyStatusPending   WithdrawalPatchBodyStatus = "pending"
	WithdrawalPatchBodyStatusConfirmed WithdrawalPatchBodyStatus = "confirmed"
	WithdrawalPatchBodyStatusRejected  WithdrawalPatchBodyStatus = "rejected"
)

// AllValues returns all WithdrawalPatchBodyStatus values.
func (WithdrawalPatchBodyStatus) AllValues() []WithdrawalPatchBodyStatus {
	return []WithdrawalPatchBodyStatus{
		WithdrawalPatchBodyStatusPending,
		WithdrawalPatchBodyStatusConfirmed,
		WithdrawalPatchBodyStatusRejected,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s WithdrawalPatchBodyStatus) MarshalText() ([]byte, error) {
	switch s {
	case WithdrawalPatchBodyStatusPending:
		return []byte(s), nil
	case WithdrawalPatchBodyStatusConfirmed:
		return []byte(s), nil
	case WithdrawalPatchBodyStatusRejected:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *WithdrawalPatchBodyStatus) UnmarshalText(data []byte) error {
	switch WithdrawalPatchBodyStatus(data) {
	case WithdrawalPatchBodyStatusPending:
		*s = WithdrawalPatchBodyStatusPending
		return nil
	case WithdrawalPatchBodyStatusConfirmed:
		*s = WithdrawalPatchBodyStatusConfirmed
		return nil
	case WithdrawalPatchBodyStatusRejected:
		*s = WithdrawalPatchBodyStatusRejected
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}
