// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"
	"net/url"

	"github.com/go-faster/errors"
	"github.com/google/uuid"

	"github.com/ogen-go/ogen/conv"
	"github.com/ogen-go/ogen/middleware"
	"github.com/ogen-go/ogen/ogenerrors"
	"github.com/ogen-go/ogen/uri"
	"github.com/ogen-go/ogen/validate"
)

// PatchWithdrawalParams is parameters of patchWithdrawal operation.
type PatchWithdrawalParams struct {
	// Withdrawal Id.
	WithdrawalId uuid.UUID
}

func unpackPatchWithdrawalParams(packed middleware.Parameters) (params PatchWithdrawalParams) {
	{
		key := middleware.ParameterKey{
			Name: "withdrawalId",
			In:   "path",
		}
		params.WithdrawalId = packed[key].(uuid.UUID)
	}
	return params
}

func decodePatchWithdrawalParams(args [1]string, argsEscaped bool, r *http.Request) (params PatchWithdrawalParams, _ error) {
	// Decode path: withdrawalId.
	if err := func() error {
		param := args[0]
		if argsEscaped {
			unescaped, err := url.PathUnescape(args[0])
			if err != nil {
				return errors.Wrap(err, "unescape path")
			}
			param = unescaped
		}
		if len(param) > 0 {
			d := uri.NewPathDecoder(uri.PathDecoderConfig{
				Param:   "withdrawalId",
				Value:   param,
				Style:   uri.PathStyleSimple,
				Explode: false,
			})

			if err := func() error {
				val, err := d.DecodeValue()
				if err != nil {
					return err
				}

				c, err := conv.ToUUID(val)
				if err != nil {
					return err
				}

				params.WithdrawalId = c
				return nil
			}(); err != nil {
				return err
			}
		} else {
			return validate.ErrFieldRequired
		}
		return nil
	}(); err != nil {
		return params, &ogenerrors.DecodeParamError{
			Name: "withdrawalId",
			In:   "path",
			Err:  err,
		}
	}
	return params, nil
}
